//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dummieHack {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dummieHack.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap pe {
            get {
                object obj = ResourceManager.GetObject("pe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Taurox es un programa diseñado para obtener de manera ilimitada documentos (libros) de la página web&gt; &quot;Libros Tauro&quot; (http://www.librostauro.com.ar/) &gt;
        ///CopyLeft (C) &lt;2012&gt;  &lt;Juan José Ruiz de Castilla&gt;
        ///
        ///Este programa es un software libre: tu puedes redistribuirlo y/o modificarlo bajo los terminos de GNU Licencia pública general publicada por the Free Software Foundation,  ya sea la versión 3 de la Licencia (GPLv3), o (a su elección) cualquier versión posterior.
        ///
        ///Este programa es distribuido con la esp [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string textoAboutES {
            get {
                return ResourceManager.GetString("textoAboutES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Taurox is a program designed for an unlimited dowload of documents (e-books) of the website&gt;&quot;Libros Tauro&quot; (http://www.librostauro.com.ar/) &gt;
        ///CopyLeft (C) &lt;2012&gt;  &lt;Juan José Ruiz de Castilla&gt;
        ///
        ///This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License (GPLv3), or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string textoAboutUS {
            get {
                return ResourceManager.GetString("textoAboutUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el link del libro que quiere descargar :.
        /// </summary>
        internal static string textoLinkDescargaES {
            get {
                return ResourceManager.GetString("textoLinkDescargaES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string textoLinkDescargaUS {
            get {
                return ResourceManager.GetString("textoLinkDescargaUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta aplicación sirve exclusivamente para obtener acceso ilimitado a la descarga de libros de la Web.
        /// </summary>
        internal static string textoPresentacionLinea1ES {
            get {
                return ResourceManager.GetString("textoPresentacionLinea1ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string textoPresentacionLinea1US {
            get {
                return ResourceManager.GetString("textoPresentacionLinea1US", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
